// seisconv-core / sps - the full offline EPSG registry.
//
// Loads the committed `epsg-registry.json` (generated by scripts/gen-epsg.ts from
// the IOGP EPSG Geodetic Parameter Dataset) and exposes it as searchable
// {@link CRS} records. Roughly 6 980 coordinate reference systems, entirely
// offline - the app never needs the network to find a projection.
//
// EVERY row carries an explicit support verdict. A CRS whose projection method
// this app cannot compute, whose axes are not easting/northing, or whose
// ellipsoid could not be resolved is still LISTED and still searchable, but
// {@link crsSupport} returns a reason and callers must refuse to reproject to it.
// Showing it with an honest "why not" beats hiding it, and both beat silently
// producing coordinates that are wrong.
//
// Pure - no DOM, no Node. This module is NOT re-exported from core/index on
// purpose: it pulls in a ~1.1 MB table that only the main process needs.

import { EXTRA_METHODS } from '../projections';
import type { CRS } from './reproject';
import registry from './epsg-registry.json';

/** One row exactly as scripts/gen-epsg.ts writes it (keys kept short for size). */
export interface EpsgRow {
  c: string;
  n: string;
  m: string;
  a?: number;
  rf?: number;
  lat0?: number;
  lon0?: number;
  lat1?: number;
  lat2?: number;
  lts?: number;
  k0?: number;
  x0?: number;
  y0?: number;
  pm?: number;
  ax?: string;
  z?: number;
  s?: 1;
  t?: number[];
  u?: number;
  d?: 1;
  noEll?: 1;
  gs?: 1;
}

const ROWS: EpsgRow[] = (registry as { rows: EpsgRow[] }).rows;

/** Methods with a working forward AND inverse: TM/UTM/GEO here, plus ./projections. */
const SUPPORTED_METHODS = new Set<string>(['TM', 'UTM', 'GEO', ...EXTRA_METHODS]);

export interface CrsSupport {
  ok: boolean;
  /** Why not, phrased for a user, when `ok` is false. */
  reason?: string;
}

/**
 * Whether this app can actually convert coordinates for a CRS - and if not, why.
 * Deliberately conservative: anything not positively known to work is refused.
 */
export function crsSupport(row: EpsgRow): CrsSupport {
  if (row.noEll) return { ok: false, reason: 'its reference ellipsoid is not in the built-in table' };
  if (row.ax) return { ok: false, reason: `its axes are ${row.ax === 'wsu' ? 'westing/southing' : row.ax}, not easting/northing, so it has no easting or northing to write` };
  if (!SUPPORTED_METHODS.has(row.m)) return { ok: false, reason: `the ${row.m} projection method is not implemented` };
  // An NTv2/NADCON grid-shift datum tie cannot be approximated by a Helmert:
  // ignoring it silently misplaces a survey by tens to hundreds of metres
  // (OSGB36 / British National Grid is ~128 m out that way). Native export still
  // works and its .prj names the CRS correctly, so the user's GIS can do the
  // shift properly - it is only OUR reprojection that must decline.
  if (row.gs) return { ok: false, reason: 'its datum tie to WGS 84 needs an NTv2/NADCON grid file, which this app does not read (a Helmert approximation would be tens of metres out)' };
  return { ok: true };
}

/** Turn a registry row into the {@link CRS} shape the rest of the app passes around. */
export function rowToCRS(row: EpsgRow): CRS {
  const isUtm = row.m === 'UTM';
  const lon0 = isUtm && row.z != null ? row.z * 6 - 183 : row.lon0;
  const crs: CRS = {
    code: 'EPSG:' + row.c,
    name: row.n,
    // `subtype` stays the legacy discriminator for the TM/UTM/GEO fast paths;
    // `method` drives everything else.
    subtype: row.m === 'UTM' ? 'UTM' : row.m === 'GEO' ? 'GEO' : row.m === 'TM' ? 'TM' : row.m,
    method: SUPPORTED_METHODS.has(row.m) && row.m !== 'TM' && row.m !== 'UTM' && row.m !== 'GEO' ? row.m : undefined,
    zone: row.z,
    hemi: isUtm ? (row.s ? 'S' : 'N') : undefined,
    a: row.a,
    f: row.rf ? 1 / row.rf : row.rf === 0 ? 0 : undefined,
    lon0,
    lat0: row.lat0,
    lat1: row.lat1,
    lat2: row.lat2,
    latTs: row.lts,
    k0: isUtm ? 0.9996 : row.k0,
    FE: isUtm ? 500000 : row.x0,
    FN: isUtm ? (row.s ? 10000000 : 0) : row.y0,
    pmOffset: row.pm,
    unitFactor: row.u,
    deprecated: row.d === 1,
  };
  if (row.t && (row.t.length === 3 || row.t.length === 7)) {
    const [dx, dy, dz, rx = 0, ry = 0, rz = 0, ds = 0] = row.t;
    // proj4's +towgs84 rotations use the POSITION VECTOR convention, matching
    // helmert7ToWGS84. A 3-parameter shift is the same thing with zero rotations.
    if (Math.abs(dx) + Math.abs(dy) + Math.abs(dz) + Math.abs(rx) + Math.abs(ry) + Math.abs(rz) + Math.abs(ds) > 0) {
      crs.helmert = { dx, dy, dz, rx, ry, rz, ds };
    }
  }
  return crs;
}

/** Look up one CRS by code ('2039', 'EPSG:2039', 2039). Null when unknown. */
export function epsgRow(code: string | number): EpsgRow | null {
  const c = String(code).replace(/^epsg:\s*/i, '').trim();
  if (!/^\d+$/.test(c)) return null;
  return ROWS.find((r) => r.c === c) ?? null;
}

/** Total number of CRSs in the shipped registry. */
export function epsgCount(): number {
  return ROWS.length;
}

export interface EpsgHit {
  crs: CRS;
  row: EpsgRow;
  support: CrsSupport;
}

export interface EpsgSearchOpts {
  /** Cap on returned rows. */
  limit?: number;
  /** Drop CRSs this app cannot compute. Default false - they are shown, greyed. */
  supportedOnly?: boolean;
  /** Drop EPSG-deprecated CRSs. Default true. */
  hideDeprecated?: boolean;
}

/**
 * Free-text search over the whole registry, ranked. Matches an EPSG code
 * (numeric, with or without the prefix) and the name, requiring every query
 * token to appear so "utm 36n" finds "WGS 84 / UTM zone 36N" even though the
 * word "zone" sits between them.
 *
 * Ranking, highest first: exact code, code prefix, whole-query substring, all
 * tokens present. Supported CRSs outrank unsupported ones at equal score, so the
 * usable answer is the one at the top.
 */
export function searchEpsgRegistry(query: string, opts: EpsgSearchOpts = {}): EpsgHit[] {
  const limit = Math.max(1, Math.min(500, opts.limit ?? 50));
  const hideDeprecated = opts.hideDeprecated !== false;
  const q = (query || '').trim().toLowerCase();
  const stripped = q.replace(/^epsg:?\s*/, '').trim();
  const isCode = /^\d+$/.test(stripped);
  const tokens = q.replace(/[^a-z0-9]+/g, ' ').trim().split(' ').filter(Boolean);

  const scored: { hit: EpsgHit; score: number }[] = [];
  for (const row of ROWS) {
    if (hideDeprecated && row.d) continue;
    const support = crsSupport(row);
    if (opts.supportedOnly && !support.ok) continue;

    let score = 0;
    if (!q) {
      score = 1; // empty query: everything is equally (un)interesting
    } else {
      if (isCode) {
        if (row.c === stripped) score += 10000;
        else if (row.c.startsWith(stripped)) score += 500;
      }
      const hay = (row.c + ' ' + row.n).toLowerCase();
      if (hay.includes(q)) score += 200;
      if (tokens.length && tokens.every((t) => hay.includes(t))) score += 50 + tokens.length * 5;
      if (!score) continue;
    }
    // A CRS we can actually use wins ties against one we would have to refuse.
    if (support.ok) score += 10;
    scored.push({ hit: { crs: rowToCRS(row), row, support }, score });
  }

  scored.sort((x, y) => y.score - x.score || Number(x.hit.row.c) - Number(y.hit.row.c));
  return scored.slice(0, limit).map((s) => s.hit);
}

/**
 * Identify an EPSG code for a CRS that carries only parameters - the case for a
 * CRS read from an SPS H-record block, which names no code.
 *
 * This matters well beyond labelling: GeoTIFF can only state a CRS cleanly by
 * EPSG code (its citation mechanism cannot carry WKT reliably), so without an
 * identified code a projected raster gets written as "user-defined" and readers
 * fall back to calling it geographic - a UTM raster that claims to be in
 * degrees. Matching is EXACT on the projection method and TIGHT on every
 * defining parameter; anything less would attach a confidently wrong code, which
 * is worse than admitting the code is unknown.
 */
export function findEpsgByParams(crs: CRS): EpsgHit | null {
  if (!crs) return null;
  const sub = (crs.subtype || '').toUpperCase();
  const method = crs.method || (sub === 'UTM' ? 'UTM' : sub === 'GEO' ? 'GEO' : sub === 'TM' ? 'TM' : '');
  if (!method) return null;

  const near = (a: number | undefined, b: number | undefined, tol: number): boolean => {
    if (a == null && b == null) return true;
    if (a == null || b == null) return false;
    return Math.abs(a - b) <= tol;
  };
  const wantA = crs.a;
  const wantRf = crs.f ? 1 / crs.f : crs.f === 0 ? 0 : undefined;
  const lon0 = crs.lon0 ?? (crs.zone != null ? crs.zone * 6 - 183 : undefined);

  const candidates: EpsgRow[] = [];
  for (const row of ROWS) {
    if (row.d || row.ax || row.noEll || row.gs) continue; // never identify AS something we would refuse
    if (row.m !== method) continue;
    // Ellipsoid must agree to a metre and to 1e-6 in 1/f - enough to separate
    // WGS 84 from GRS 1980, which differ only in the sixth decimal of 1/f.
    if (!near(row.a, wantA, 1)) continue;
    if (!near(row.rf, wantRf, 1e-6)) continue;
    if (row.u) continue; // a metre-based CRS never identifies as a feet grid
    if (method === 'UTM') {
      if (row.z !== crs.zone) continue;
      if ((row.s ? 'S' : 'N') !== (crs.hemi || 'N')) continue;
    } else if (method !== 'GEO') {
      const rowLon0 = row.lon0 ?? (row.z != null ? row.z * 6 - 183 : undefined);
      if (!near(rowLon0, lon0, 1e-7)) continue;
      if (!near(row.lat0, crs.lat0, 1e-7)) continue;
      if (!near(row.k0, crs.k0, 1e-9)) continue;
      if (!near(row.x0, crs.FE, 1e-3)) continue;
      if (!near(row.y0, crs.FN, 1e-3)) continue;
    }
    candidates.push(row);
  }
  if (!candidates.length) return null;
  // Several datums can share one grid definition (e.g. every WGS84-ellipsoid UTM
  // zone). Prefer the one whose datum shift matches, then the lowest code for a
  // stable, reproducible answer.
  const hasShift = !!crs.helmert && Math.abs(crs.helmert.dx) + Math.abs(crs.helmert.dy) + Math.abs(crs.helmert.dz) > 0.01;
  const shiftMatches = (r: EpsgRow) => {
    const rowShift = !!r.t && r.t.slice(0, 3).some((v) => Math.abs(v) > 0.01);
    return rowShift === hasShift;
  };
  // Several codes can be parameter-IDENTICAL: "WGS 84 / TMzn36N" (EPSG:4038) is
  // numerically the same grid as "WGS 84 / UTM zone 36N" (EPSG:32636). Picking by
  // lowest code alone returned the obscure alias, so prefer the canonical name
  // first. Purely a labelling preference - every candidate here computes the same
  // coordinates.
  const canonical = (r: EpsgRow) => (method === 'UTM' ? /UTM zone/i.test(r.n) : true);
  candidates.sort(
    (a, b) =>
      Number(canonical(b)) - Number(canonical(a)) ||
      Number(shiftMatches(b)) - Number(shiftMatches(a)) ||
      Number(a.c) - Number(b.c),
  );
  const row = candidates[0];
  return { crs: rowToCRS(row), row, support: crsSupport(row) };
}

/** Resolve one CRS by code, with its support verdict. Null when unknown. */
export function getEpsg(code: string | number): EpsgHit | null {
  const row = epsgRow(code);
  if (!row) return null;
  return { crs: rowToCRS(row), row, support: crsSupport(row) };
}
